[Back] Change openshift cartridge to DIY to enable WebSocket - hourray

diff --git a/dist/.openshift/action_hooks/post_deploy b/dist/.openshift/action_hooks/post_deploy
--- a/dist/.openshift/action_hooks/post_deploy
+++ b/dist/.openshift/action_hooks/post_deploy
@@ -2,3 +2,33 @@
 # This is a simple post deploy hook executed after your application
 # is deployed and started.  This script gets executed directly, so 
 # it could be python, php, ruby, etc.
+
+source $OPENSHIFT_CARTRIDGE_SDK_BASH
+
+set -e
+
+if [ ! -z "$OPENSHIFT_POSTGRESQL_DB_HOST" ]; then
+    export RAILS_DB="postgresql"
+fi
+
+if [ ! -z "$OPENSHIFT_MYSQL_DB_HOST" ]; then
+    export RAILS_DB="mysql"
+fi
+
+if [ -z "$RAILS_DB" ]; then
+  echo 1>&2
+  echo "Could not find the database cartridge. Please run:" 1>&2
+  echo "rhc cartridge add -a $OPENSHIFT_APP_NAME -c mysql-5.1" 1>&2
+  echo "or"
+  echo "rhc cartridge add -a $OPENSHIFT_APP_NAME -c postgresql-9.2" 1>&2
+  echo "then make a sample commit (add whitespace somewhere) and re-push" 1>&2
+  echo 1>&2
+  exit 5
+fi
+
+# this will spawn a sub-shell, so make sure we can use rvm
+source $OPENSHIFT_DATA_DIR/.rvm/scripts/rvm
+
+pushd ${OPENSHIFT_REPO_DIR} > /dev/null
+RAILS_ENV=production bundle exec rake db:migrate
+popd > /dev/null
